version: "3.8"
services:
  php-service:
    container_name: d-php-service
    build:
      args:
        user: prod
        uid: 1000
      context: .
      dockerfile: ./dockerfiles/dockerfile.dev
    image: p-php-image
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./service:/var/www
  web_server:
    container_name: p-php-server
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./service:/var/www
      - ./nginx/laravel.conf:/etc/nginx/conf.d/default.conf
networks:
  default:
    external:
      name: main
